#shell格式
FROM ubuntu
ENV name Docker
ENTRYPOINT echo "hello $name"

#exec格式
#ENTRYPOINT ["/bin/bash","-c","echo hello $name"]
#docker login 登陆
#docker image push 949429516/hello-world  推送docker,/之前必须是用户名